<?php

declare(strict_types=1);

use App\Controller\WelcomeController;

?>
<!DOCTYPE html>
<html lang="<?= ${WelcomeController::LANGUAGE_CODE_VAR_NAME} ?>">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Awesome Skeleton</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        h1 {
            margin-bottom: 1rem;
        }
        .greeting-container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
    </style>
</head>
<body>
<div class="greeting-container">
    <h1><?= ${WelcomeController::GREETING_MESSAGE_VAR_NAME} ?></h1>
    <p><a href="https://dev.sunrise-studio.io/">What's next?</a></p>
</div>
</body>
</html>
